#!/usr/bin/env python3
"""Additional compact translation catalogs for Wine4Office Manager."""

from __future__ import annotations


LANGUAGES = (
    "de", "es", "fr", "it", "pt", "nl", "ru", "uk", "pl", "tr",
    "zh", "zh_Hant", "ja", "ko",
)

# English source followed by translations in LANGUAGES order. Product names,
# paths, version strings, and diagnostics intentionally remain unchanged.
ROWS = (
    ("Wine4Office Manager", "Wine4Office-Verwaltung", "Administrador de Wine4Office", "Gestionnaire Wine4Office", "Gestore Wine4Office", "Gerenciador Wine4Office", "Wine4Office-beheer", "Менеджер Wine4Office", "Менеджер Wine4Office", "Menedżer Wine4Office", "Wine4Office Yöneticisi", "Wine4Office 管理器", "Wine4Office 管理員", "Wine4Office マネージャー", "Wine4Office 관리자"),
    ("Checking…", "Wird geprüft…", "Comprobando…", "Vérification…", "Controllo…", "Verificando…", "Controleren…", "Проверка…", "Перевірка…", "Sprawdzanie…", "Denetleniyor…", "正在检查…", "正在檢查…", "確認中…", "확인 중…"),
    ("Ready", "Bereit", "Listo", "Prêt", "Pronto", "Pronto", "Gereed", "Готово", "Готово", "Gotowe", "Hazır", "就绪", "就緒", "準備完了", "준비됨"),
    ("Environment", "Umgebung", "Entorno", "Environnement", "Ambiente", "Ambiente", "Omgeving", "Среда", "Середовище", "Środowisko", "Ortam", "环境", "環境", "環境", "환경"),
    ("Install Office & Teams", "Office & Teams installieren", "Instalar Office y Teams", "Installer Office et Teams", "Installa Office e Teams", "Instalar o Office e o Teams", "Office & Teams installeren", "Установить Office и Teams", "Установити Office і Teams", "Zainstaluj Office i Teams", "Office ve Teams'i yükle", "安装 Office 和 Teams", "安裝 Office 和 Teams", "Office と Teams をインストール", "Office 및 Teams 설치"),
    ("Applications", "Anwendungen", "Aplicaciones", "Applications", "Applicazioni", "Aplicativos", "Toepassingen", "Приложения", "Програми", "Aplikacje", "Uygulamalar", "应用程序", "應用程式", "アプリケーション", "응용 프로그램"),
    ("Office settings", "Office-Einstellungen", "Configuración de Office", "Paramètres Office", "Impostazioni di Office", "Configurações do Office", "Office-instellingen", "Настройки Office", "Налаштування Office", "Ustawienia Office", "Office ayarları", "Office 设置", "Office 設定", "Office の設定", "Office 설정"),
    ("Wine tools", "Wine-Werkzeuge", "Herramientas de Wine", "Outils Wine", "Strumenti Wine", "Ferramentas do Wine", "Wine-hulpmiddelen", "Инструменты Wine", "Інструменти Wine", "Narzędzia Wine", "Wine araçları", "Wine 工具", "Wine 工具", "Wine ツール", "Wine 도구"),
    ("Maintenance", "Wartung", "Mantenimiento", "Maintenance", "Manutenzione", "Manutenção", "Onderhoud", "Обслуживание", "Обслуговування", "Konserwacja", "Bakım", "维护", "維護", "メンテナンス", "유지 관리"),
    ("Browse…", "Durchsuchen…", "Examinar…", "Parcourir…", "Sfoglia…", "Procurar…", "Bladeren…", "Обзор…", "Огляд…", "Przeglądaj…", "Gözat…", "浏览…", "瀏覽…", "参照…", "찾아보기…"),
    ("Choose a directory", "Ordner auswählen", "Elegir una carpeta", "Choisir un dossier", "Scegli una cartella", "Escolher uma pasta", "Map kiezen", "Выбрать папку", "Вибрати папку", "Wybierz folder", "Klasör seç", "选择文件夹", "選擇資料夾", "フォルダーを選択", "폴더 선택"),
    ("Choose a file", "Datei auswählen", "Elegir un archivo", "Choisir un fichier", "Scegli un file", "Escolher um arquivo", "Bestand kiezen", "Выбрать файл", "Вибрати файл", "Wybierz plik", "Dosya seç", "选择文件", "選擇檔案", "ファイルを選択", "파일 선택"),
    ("Wine environment", "Wine-Umgebung", "Entorno de Wine", "Environnement Wine", "Ambiente Wine", "Ambiente Wine", "Wine-omgeving", "Среда Wine", "Середовище Wine", "Środowisko Wine", "Wine ortamı", "Wine 环境", "Wine 環境", "Wine 環境", "Wine 환경"),
    ("Choose the Wine4Office runner and the isolated environment used for Microsoft Office.", "Wählen Sie den Wine4Office-Runner und die isolierte Umgebung für Microsoft Office.", "Elija el ejecutor de Wine4Office y el entorno aislado para Microsoft Office.", "Choisissez l'exécuteur Wine4Office et l'environnement isolé utilisé par Microsoft Office.", "Scegli il runner Wine4Office e l'ambiente isolato usato per Microsoft Office.", "Escolha o executor do Wine4Office e o ambiente isolado usado pelo Microsoft Office.", "Kies de Wine4Office-runner en de geïsoleerde omgeving voor Microsoft Office.", "Выберите Wine4Office и изолированную среду для Microsoft Office.", "Виберіть Wine4Office та ізольоване середовище для Microsoft Office.", "Wybierz program Wine4Office i izolowane środowisko dla Microsoft Office.", "Wine4Office çalıştırıcısını ve Microsoft Office için yalıtılmış ortamı seçin.", "选择 Wine4Office 运行程序及 Microsoft Office 使用的隔离环境。", "選擇 Wine4Office 執行程式及 Microsoft Office 使用的隔離環境。", "Wine4Office ランナーと Microsoft Office 用の分離環境を選択します。", "Wine4Office 실행기와 Microsoft Office용 격리 환경을 선택하세요."),
    ("Environment paths", "Umgebungspfade", "Rutas del entorno", "Chemins de l'environnement", "Percorsi dell'ambiente", "Caminhos do ambiente", "Omgevingspaden", "Пути среды", "Шляхи середовища", "Ścieżki środowiska", "Ortam yolları", "环境路径", "環境路徑", "環境のパス", "환경 경로"),
    ("Environment:", "Umgebung:", "Entorno:", "Environnement :", "Ambiente:", "Ambiente:", "Omgeving:", "Среда:", "Середовище:", "Środowisko:", "Ortam:", "环境：", "環境：", "環境:", "환경:"),
    ("Wine executable:", "Wine-Programm:", "Ejecutable de Wine:", "Exécutable Wine :", "Eseguibile Wine:", "Executável do Wine:", "Wine-programma:", "Исполняемый файл Wine:", "Виконуваний файл Wine:", "Plik wykonywalny Wine:", "Wine yürütülebiliri:", "Wine 可执行文件：", "Wine 執行檔：", "Wine 実行ファイル:", "Wine 실행 파일:"),
    ("Launch Wine4Office through X11 (uncheck for native Wayland)", "Wine4Office über X11 starten (für natives Wayland abwählen)", "Iniciar Wine4Office mediante X11 (desmarcar para Wayland nativo)", "Lancer Wine4Office via X11 (décocher pour Wayland natif)", "Avvia Wine4Office tramite X11 (deseleziona per Wayland nativo)", "Iniciar o Wine4Office via X11 (desmarque para Wayland nativo)", "Wine4Office via X11 starten (uitvinken voor native Wayland)", "Запускать Wine4Office через X11 (снимите флажок для Wayland)", "Запускати Wine4Office через X11 (зніміть позначку для Wayland)", "Uruchamiaj Wine4Office przez X11 (odznacz dla Wayland)", "Wine4Office'ı X11 üzerinden başlat (doğal Wayland için işareti kaldır)", "通过 X11 启动 Wine4Office（取消勾选以使用原生 Wayland）", "透過 X11 啟動 Wine4Office（取消勾選以使用原生 Wayland）", "X11 経由で Wine4Office を起動（ネイティブ Wayland ではオフ）", "X11을 통해 Wine4Office 실행(네이티브 Wayland는 선택 해제)"),
    ("Create", "Erstellen", "Crear", "Créer", "Crea", "Criar", "Maken", "Создать", "Створити", "Utwórz", "Oluştur", "创建", "建立", "作成", "만들기"),
    ("Recreate…", "Neu erstellen…", "Volver a crear…", "Recréer…", "Ricrea…", "Recriar…", "Opnieuw maken…", "Пересоздать…", "Створити заново…", "Utwórz ponownie…", "Yeniden oluştur…", "重新创建…", "重新建立…", "再作成…", "다시 만들기…"),
    ("Stop Wine", "Wine beenden", "Detener Wine", "Arrêter Wine", "Arresta Wine", "Parar o Wine", "Wine stoppen", "Остановить Wine", "Зупинити Wine", "Zatrzymaj Wine", "Wine'ı durdur", "停止 Wine", "停止 Wine", "Wine を停止", "Wine 중지"),
    ("Save paths", "Pfade speichern", "Guardar rutas", "Enregistrer les chemins", "Salva percorsi", "Salvar caminhos", "Paden opslaan", "Сохранить пути", "Зберегти шляхи", "Zapisz ścieżki", "Yolları kaydet", "保存路径", "儲存路徑", "パスを保存", "경로 저장"),
    ("Background services", "Hintergrunddienste", "Servicios en segundo plano", "Services en arrière-plan", "Servizi in background", "Serviços em segundo plano", "Achtergrondservices", "Фоновые службы", "Фонові служби", "Usługi w tle", "Arka plan hizmetleri", "后台服务", "背景服務", "バックグラウンドサービス", "백그라운드 서비스"),
    ("Start Office Click-to-Run and App-V services at login. Uses about 300–600 MB of RAM and makes Office apps open 2–3× faster.", "Office Click-to-Run und App-V bei der Anmeldung starten. Benötigt etwa 300–600 MB RAM und öffnet Office-Anwendungen 2–3× schneller.", "Inicia los servicios Click-to-Run y App-V de Office al iniciar sesión. Usa unos 300–600 MB de RAM y abre Office 2–3 veces más rápido.", "Démarre les services Office Click-to-Run et App-V à la connexion. Utilise environ 300 à 600 Mo de RAM et accélère l'ouverture d'Office de 2 à 3 fois.", "Avvia i servizi Office Click-to-Run e App-V all'accesso. Usa circa 300–600 MB di RAM e apre Office 2–3 volte più velocemente.", "Inicia os serviços Office Click-to-Run e App-V ao entrar. Usa cerca de 300–600 MB de RAM e abre o Office 2–3 vezes mais rápido.", "Start Office Click-to-Run en App-V bij aanmelden. Gebruikt circa 300–600 MB RAM en opent Office 2–3× sneller.", "Запускает службы Office Click-to-Run и App-V при входе. Использует около 300–600 МБ ОЗУ и ускоряет запуск Office в 2–3 раза.", "Запускає служби Office Click-to-Run і App-V під час входу. Використовує близько 300–600 МБ ОЗП і пришвидшує запуск Office у 2–3 рази.", "Uruchamia usługi Office Click-to-Run i App-V przy logowaniu. Używa około 300–600 MB RAM i otwiera Office 2–3 razy szybciej.", "Office Click-to-Run ve App-V hizmetlerini oturum açarken başlatır. Yaklaşık 300–600 MB RAM kullanır ve Office'i 2–3 kat hızlı açar.", "登录时启动 Office Click-to-Run 和 App-V 服务。约占用 300–600 MB 内存，使 Office 的启动速度提高 2–3 倍。", "登入時啟動 Office Click-to-Run 和 App-V 服務。約使用 300–600 MB 記憶體，使 Office 的啟動速度提高 2–3 倍。", "ログイン時に Office Click-to-Run と App-V サービスを開始します。約 300～600 MB の RAM を使用し、Office を 2～3 倍速く開きます。", "로그인할 때 Office Click-to-Run 및 App-V 서비스를 시작합니다. 약 300~600MB RAM을 사용하며 Office를 2~3배 빠르게 엽니다."),
    ("Selected environment:", "Ausgewählte Umgebung:", "Entorno seleccionado:", "Environnement sélectionné :", "Ambiente selezionato:", "Ambiente selecionado:", "Geselecteerde omgeving:", "Выбранная среда:", "Вибране середовище:", "Wybrane środowisko:", "Seçili ortam:", "所选环境：", "所選環境：", "選択した環境:", "선택한 환경:"),
    ("Bound environment:", "Gebundene Umgebung:", "Entorno vinculado:", "Environnement lié :", "Ambiente associato:", "Ambiente vinculado:", "Gekoppelde omgeving:", "Привязанная среда:", "Прив'язане середовище:", "Powiązane środowisko:", "Bağlı ortam:", "绑定环境：", "繫結環境：", "関連付けた環境:", "연결된 환경:"),
    ("RAM usage:", "RAM-Nutzung:", "Uso de RAM:", "Utilisation de la RAM :", "Uso RAM:", "Uso de RAM:", "RAM-gebruik:", "Использование ОЗУ:", "Використання ОЗП:", "Użycie RAM:", "RAM kullanımı:", "内存使用：", "記憶體使用：", "RAM 使用量:", "RAM 사용량:"),
    ("Not configured", "Nicht konfiguriert", "Sin configurar", "Non configuré", "Non configurato", "Não configurado", "Niet geconfigureerd", "Не настроено", "Не налаштовано", "Nie skonfigurowano", "Yapılandırılmadı", "未配置", "尚未設定", "未設定", "구성되지 않음"),
    ("Systemd user services are unavailable.", "Systemd-Benutzerdienste sind nicht verfügbar.", "Los servicios de usuario de systemd no están disponibles.", "Les services utilisateur systemd ne sont pas disponibles.", "I servizi utente systemd non sono disponibili.", "Os serviços de usuário do systemd não estão disponíveis.", "Systemd-gebruikersservices zijn niet beschikbaar.", "Пользовательские службы systemd недоступны.", "Користувацькі служби systemd недоступні.", "Usługi użytkownika systemd są niedostępne.", "Systemd kullanıcı hizmetleri kullanılamıyor.", "systemd 用户服务不可用。", "systemd 使用者服務無法使用。", "systemd ユーザーサービスを利用できません。", "systemd 사용자 서비스를 사용할 수 없습니다."),
    ("Enable && start", "Aktivieren && starten", "Activar e iniciar", "Activer et démarrer", "Abilita e avvia", "Ativar e iniciar", "Inschakelen en starten", "Включить и запустить", "Увімкнути й запустити", "Włącz i uruchom", "Etkinleştir ve başlat", "启用并启动", "啟用並啟動", "有効化して開始", "활성화 및 시작"),
    ("Stop && disable", "Stoppen && deaktivieren", "Detener y desactivar", "Arrêter et désactiver", "Arresta e disabilita", "Parar e desativar", "Stoppen en uitschakelen", "Остановить и отключить", "Зупинити й вимкнути", "Zatrzymaj i wyłącz", "Durdur ve devre dışı bırak", "停止并禁用", "停止並停用", "停止して無効化", "중지 및 비활성화"),
    ("Run a Windows executable", "Windows-Programm ausführen", "Ejecutar un programa de Windows", "Exécuter un programme Windows", "Esegui un programma Windows", "Executar um programa do Windows", "Windows-programma uitvoeren", "Запустить программу Windows", "Запустити програму Windows", "Uruchom program Windows", "Windows programı çalıştır", "运行 Windows 程序", "執行 Windows 程式", "Windows プログラムを実行", "Windows 프로그램 실행"),
    ("Executable:", "Programm:", "Ejecutable:", "Exécutable :", "Eseguibile:", "Executável:", "Programma:", "Программа:", "Програма:", "Program:", "Yürütülebilir:", "可执行文件：", "執行檔：", "実行ファイル:", "실행 파일:"),
    ("Arguments:", "Argumente:", "Argumentos:", "Arguments :", "Argomenti:", "Argumentos:", "Argumenten:", "Аргументы:", "Аргументи:", "Argumenty:", "Bağımsız değişkenler:", "参数：", "引數：", "引数:", "인수:"),
    ("Working folder:", "Arbeitsordner:", "Carpeta de trabajo:", "Dossier de travail :", "Cartella di lavoro:", "Pasta de trabalho:", "Werkmap:", "Рабочая папка:", "Робоча папка:", "Folder roboczy:", "Çalışma klasörü:", "工作文件夹：", "工作資料夾：", "作業フォルダー:", "작업 폴더:"),
    ("Example: /configure \"/home/user/office.xml\"", "Beispiel: /configure \"/home/user/office.xml\"", "Ejemplo: /configure \"/home/user/office.xml\"", "Exemple : /configure \"/home/user/office.xml\"", "Esempio: /configure \"/home/user/office.xml\"", "Exemplo: /configure \"/home/user/office.xml\"", "Voorbeeld: /configure \"/home/user/office.xml\"", "Пример: /configure \"/home/user/office.xml\"", "Приклад: /configure \"/home/user/office.xml\"", "Przykład: /configure \"/home/user/office.xml\"", "Örnek: /configure \"/home/user/office.xml\"", "示例：/configure \"/home/user/office.xml\"", "範例：/configure \"/home/user/office.xml\"", "例: /configure \"/home/user/office.xml\"", "예: /configure \"/home/user/office.xml\""),
    ("Optional; defaults to the executable's folder", "Optional; standardmäßig der Ordner des Programms", "Opcional; se usa la carpeta del ejecutable", "Facultatif ; utilise le dossier de l'exécutable", "Facoltativa; usa la cartella dell'eseguibile", "Opcional; usa a pasta do executável", "Optioneel; standaard de map van het programma", "Необязательно; по умолчанию папка программы", "Необов'язково; типово папка програми", "Opcjonalnie; domyślnie folder programu", "İsteğe bağlı; varsayılan olarak program klasörü", "可选；默认为可执行文件所在文件夹", "選用；預設為執行檔所在資料夾", "任意。既定では実行ファイルのフォルダー", "선택 사항, 기본값은 실행 파일 폴더"),
    ("Choose and run…", "Auswählen und starten…", "Elegir y ejecutar…", "Choisir et exécuter…", "Scegli ed esegui…", "Escolher e executar…", "Kiezen en uitvoeren…", "Выбрать и запустить…", "Вибрати й запустити…", "Wybierz i uruchom…", "Seç ve çalıştır…", "选择并运行…", "選擇並執行…", "選択して実行…", "선택하여 실행…"),
    ("Run", "Starten", "Ejecutar", "Exécuter", "Esegui", "Executar", "Uitvoeren", "Запустить", "Запустити", "Uruchom", "Çalıştır", "运行", "執行", "実行", "실행"),
    ("Install Microsoft Office", "Microsoft Office installieren", "Instalar Microsoft Office", "Installer Microsoft Office", "Installa Microsoft Office", "Instalar o Microsoft Office", "Microsoft Office installeren", "Установить Microsoft Office", "Установити Microsoft Office", "Zainstaluj Microsoft Office", "Microsoft Office'ı yükle", "安装 Microsoft Office", "安裝 Microsoft Office", "Microsoft Office をインストール", "Microsoft Office 설치"),
    ("Office Deployment Tool", "Office-Bereitstellungstool", "Herramienta de implementación de Office", "Outil Déploiement d’Office", "Strumento di distribuzione di Office", "Ferramenta de Implantação do Office", "Office-implementatieprogramma", "Средство развертывания Office", "Засіб розгортання Office", "Narzędzie wdrażania pakietu Office", "Office Dağıtım Aracı", "Office 部署工具", "Office 部署工具", "Office 展開ツール", "Office 배포 도구"),
    ("Product:", "Produkt:", "Producto:", "Produit :", "Prodotto:", "Produto:", "Product:", "Продукт:", "Продукт:", "Produkt:", "Ürün:", "产品：", "產品：", "製品:", "제품:"),
    ("Languages:", "Sprachen:", "Idiomas:", "Langues :", "Lingue:", "Idiomas:", "Talen:", "Языки:", "Мови:", "Języki:", "Diller:", "语言：", "語言：", "言語:", "언어:"),
    ("Office applications", "Office-Anwendungen", "Aplicaciones de Office", "Applications Office", "Applicazioni Office", "Aplicativos do Office", "Office-toepassingen", "Приложения Office", "Програми Office", "Aplikacje Office", "Office uygulamaları", "Office 应用程序", "Office 應用程式", "Office アプリケーション", "Office 응용 프로그램"),
    ("Application", "Anwendung", "Aplicación", "Application", "Applicazione", "Aplicativo", "Toepassing", "Приложение", "Програма", "Aplikacja", "Uygulama", "应用程序", "應用程式", "アプリケーション", "응용 프로그램"),
    ("Installation status", "Installationsstatus", "Estado de instalación", "État de l'installation", "Stato installazione", "Status da instalação", "Installatiestatus", "Состояние установки", "Стан встановлення", "Stan instalacji", "Kurulum durumu", "安装状态", "安裝狀態", "インストール状態", "설치 상태"),
    ("Also place shortcuts on the Desktop", "Verknüpfungen auch auf dem Desktop ablegen", "Colocar accesos directos también en el escritorio", "Placer aussi les raccourcis sur le bureau", "Crea collegamenti anche sul desktop", "Também colocar atalhos na área de trabalho", "Ook snelkoppelingen op het bureaublad plaatsen", "Также создать ярлыки на рабочем столе", "Також створити ярлики на стільниці", "Umieść skróty także na pulpicie", "Kısayolları masaüstüne de yerleştir", "同时在桌面创建快捷方式", "同時在桌面建立捷徑", "デスクトップにもショートカットを作成", "바탕 화면에도 바로 가기 만들기"),
    ("Create or update shortcuts", "Verknüpfungen erstellen oder aktualisieren", "Crear o actualizar accesos directos", "Créer ou mettre à jour les raccourcis", "Crea o aggiorna collegamenti", "Criar ou atualizar atalhos", "Snelkoppelingen maken of bijwerken", "Создать или обновить ярлыки", "Створити або оновити ярлики", "Utwórz lub zaktualizuj skróty", "Kısayol oluştur veya güncelle", "创建或更新快捷方式", "建立或更新捷徑", "ショートカットを作成または更新", "바로 가기 만들기 또는 업데이트"),
    ("Remove shortcuts", "Verknüpfungen entfernen", "Eliminar accesos directos", "Supprimer les raccourcis", "Rimuovi collegamenti", "Remover atalhos", "Snelkoppelingen verwijderen", "Удалить ярлыки", "Видалити ярлики", "Usuń skróty", "Kısayolları kaldır", "删除快捷方式", "移除捷徑", "ショートカットを削除", "바로 가기 제거"),
    ("Launch selected", "Auswahl starten", "Iniciar selección", "Lancer la sélection", "Avvia selezionato", "Iniciar selecionado", "Selectie starten", "Запустить выбранное", "Запустити вибране", "Uruchom wybrane", "Seçileni başlat", "启动所选项目", "啟動所選項目", "選択項目を起動", "선택 항목 실행"),
    ("Compatibility", "Kompatibilität", "Compatibilidad", "Compatibilité", "Compatibilità", "Compatibilidade", "Compatibiliteit", "Совместимость", "Сумісність", "Zgodność", "Uyumluluk", "兼容性", "相容性", "互換性", "호환성"),
    ("Security", "Sicherheit", "Seguridad", "Sécurité", "Sicurezza", "Segurança", "Beveiliging", "Безопасность", "Безпека", "Zabezpieczenia", "Güvenlik", "安全", "安全性", "セキュリティ", "보안"),
    ("Privacy & cloud", "Datenschutz und Cloud", "Privacidad y nube", "Confidentialité et cloud", "Privacy e cloud", "Privacidade e nuvem", "Privacy en cloud", "Конфиденциальность и облако", "Конфіденційність і хмара", "Prywatność i chmura", "Gizlilik ve bulut", "隐私和云", "隱私權與雲端", "プライバシーとクラウド", "개인 정보 및 클라우드"),
    ("Wine Configuration", "Wine-Konfiguration", "Configuración de Wine", "Configuration de Wine", "Configurazione Wine", "Configuração do Wine", "Wine-configuratie", "Настройка Wine", "Налаштування Wine", "Konfiguracja Wine", "Wine yapılandırması", "Wine 配置", "Wine 設定", "Wine 設定", "Wine 구성"),
    ("Registry Editor", "Registrierungseditor", "Editor del registro", "Éditeur du registre", "Editor del registro", "Editor do Registro", "Register-editor", "Редактор реестра", "Редактор реєстру", "Edytor rejestru", "Kayıt Defteri Düzenleyicisi", "注册表编辑器", "登錄編輯程式", "レジストリエディター", "레지스트리 편집기"),
    ("Control Panel", "Systemsteuerung", "Panel de control", "Panneau de configuration", "Pannello di controllo", "Painel de Controle", "Configuratiescherm", "Панель управления", "Панель керування", "Panel sterowania", "Denetim Masası", "控制面板", "控制台", "コントロール パネル", "제어판"),
    ("File Explorer", "Datei-Explorer", "Explorador de archivos", "Explorateur de fichiers", "Esplora file", "Explorador de Arquivos", "Bestandsverkenner", "Проводник", "Файловий провідник", "Eksplorator plików", "Dosya Gezgini", "文件资源管理器", "檔案總管", "ファイル エクスプローラー", "파일 탐색기"),
    ("Command Prompt", "Eingabeaufforderung", "Símbolo del sistema", "Invite de commandes", "Prompt dei comandi", "Prompt de Comando", "Opdrachtprompt", "Командная строка", "Командний рядок", "Wiersz polecenia", "Komut İstemi", "命令提示符", "命令提示字元", "コマンド プロンプト", "명령 프롬프트"),
    ("Task Manager", "Task-Manager", "Administrador de tareas", "Gestionnaire des tâches", "Gestione attività", "Gerenciador de Tarefas", "Taakbeheer", "Диспетчер задач", "Диспетчер завдань", "Menedżer zadań", "Görev Yöneticisi", "任务管理器", "工作管理員", "タスク マネージャー", "작업 관리자"),
    ("Uninstaller", "Deinstallation", "Desinstalador", "Programme de désinstallation", "Programma di disinstallazione", "Desinstalador", "Verwijderprogramma", "Удаление программ", "Видалення програм", "Deinstalator", "Kaldırıcı", "卸载程序", "解除安裝程式", "アンインストーラー", "제거 프로그램"),
    ("Updates", "Aktualisierungen", "Actualizaciones", "Mises à jour", "Aggiornamenti", "Atualizações", "Updates", "Обновления", "Оновлення", "Aktualizacje", "Güncellemeler", "更新", "更新", "更新", "업데이트"),
    ("Installed versions:", "Installierte Versionen:", "Versiones instaladas:", "Versions installées :", "Versioni installate:", "Versões instaladas:", "Geïnstalleerde versies:", "Установленные версии:", "Встановлені версії:", "Zainstalowane wersje:", "Yüklü sürümler:", "已安装版本：", "已安裝版本：", "インストール済みバージョン:", "설치된 버전:"),
    ("Check for updates…", "Nach Updates suchen…", "Buscar actualizaciones…", "Rechercher des mises à jour…", "Controlla aggiornamenti…", "Verificar atualizações…", "Controleren op updates…", "Проверить обновления…", "Перевірити оновлення…", "Sprawdź aktualizacje…", "Güncellemeleri denetle…", "检查更新…", "檢查更新…", "更新を確認…", "업데이트 확인…"),
    ("Removal", "Entfernen", "Eliminación", "Suppression", "Rimozione", "Remoção", "Verwijderen", "Удаление", "Видалення", "Usuwanie", "Kaldırma", "移除", "移除", "削除", "제거"),
    ("Remove Wine4Office…", "Wine4Office entfernen…", "Eliminar Wine4Office…", "Supprimer Wine4Office…", "Rimuovi Wine4Office…", "Remover Wine4Office…", "Wine4Office verwijderen…", "Удалить Wine4Office…", "Видалити Wine4Office…", "Usuń Wine4Office…", "Wine4Office'ı kaldır…", "移除 Wine4Office…", "移除 Wine4Office…", "Wine4Office を削除…", "Wine4Office 제거…"),
    ("Operation log", "Vorgangsprotokoll", "Registro de operaciones", "Journal des opérations", "Registro operazioni", "Registro de operações", "Bewerkingslogboek", "Журнал операций", "Журнал операцій", "Dziennik operacji", "İşlem günlüğü", "操作日志", "操作記錄", "操作ログ", "작업 로그"),
    ("No operation running.", "Kein Vorgang aktiv.", "No hay ninguna operación en curso.", "Aucune opération en cours.", "Nessuna operazione in corso.", "Nenhuma operação em execução.", "Geen bewerking actief.", "Нет активных операций.", "Немає активних операцій.", "Brak aktywnej operacji.", "Çalışan işlem yok.", "没有正在运行的操作。", "沒有正在執行的操作。", "実行中の操作はありません。", "실행 중인 작업이 없습니다."),
    ("Cancel operation", "Vorgang abbrechen", "Cancelar operación", "Annuler l'opération", "Annulla operazione", "Cancelar operação", "Bewerking annuleren", "Отменить операцию", "Скасувати операцію", "Anuluj operację", "İşlemi iptal et", "取消操作", "取消操作", "操作をキャンセル", "작업 취소"),
    ("Installed", "Installiert", "Instalado", "Installé", "Installato", "Instalado", "Geïnstalleerd", "Установлено", "Встановлено", "Zainstalowano", "Yüklü", "已安装", "已安裝", "インストール済み", "설치됨"),
    ("Environment ready", "Umgebung bereit", "Entorno listo", "Environnement prêt", "Ambiente pronto", "Ambiente pronto", "Omgeving gereed", "Среда готова", "Середовище готове", "Środowisko gotowe", "Ortam hazır", "环境就绪", "環境就緒", "環境の準備完了", "환경 준비됨"),
    ("Wine runner missing", "Wine-Runner fehlt", "Falta el ejecutor de Wine", "Exécuteur Wine manquant", "Runner Wine mancante", "Executor do Wine ausente", "Wine-runner ontbreekt", "Компонент Wine отсутствует", "Компонент Wine відсутній", "Brak programu Wine", "Wine çalıştırıcısı eksik", "缺少 Wine 运行程序", "缺少 Wine 執行程式", "Wine ランナーがありません", "Wine 실행기가 없습니다"),
    ("Environment not created", "Umgebung nicht erstellt", "Entorno no creado", "Environnement non créé", "Ambiente non creato", "Ambiente não criado", "Omgeving niet gemaakt", "Среда не создана", "Середовище не створено", "Środowisko nieutworzone", "Ortam oluşturulmadı", "尚未创建环境", "尚未建立環境", "環境が作成されていません", "환경이 생성되지 않았습니다"),
    ("Status unavailable", "Status nicht verfügbar", "Estado no disponible", "État indisponible", "Stato non disponibile", "Status indisponível", "Status niet beschikbaar", "Состояние недоступно", "Стан недоступний", "Stan niedostępny", "Durum kullanılamıyor", "状态不可用", "狀態無法使用", "状態を取得できません", "상태를 확인할 수 없습니다"),
    ("Download and install", "Herunterladen und installieren", "Descargar e instalar", "Télécharger et installer", "Scarica e installa", "Baixar e instalar", "Downloaden en installeren", "Скачать и установить", "Завантажити й установити", "Pobierz i zainstaluj", "İndir ve yükle", "下载并安装", "下載並安裝", "ダウンロードしてインストール", "다운로드 및 설치"),
    ("Later", "Später", "Más tarde", "Plus tard", "Più tardi", "Mais tarde", "Later", "Позже", "Пізніше", "Później", "Daha sonra", "稍后", "稍後", "後で", "나중에"),
    ("Close", "Schließen", "Cerrar", "Fermer", "Chiudi", "Fechar", "Sluiten", "Закрыть", "Закрити", "Zamknij", "Kapat", "关闭", "關閉", "閉じる", "닫기"),
)


def catalogs() -> dict[str, dict[str, str]]:
    result = {language: {} for language in LANGUAGES}
    for row in ROWS:
        source, *translations = row
        if len(translations) != len(LANGUAGES):
            raise ValueError(f"Translation row has the wrong length: {source}")
        for language, translated in zip(LANGUAGES, translations, strict=True):
            result[language][source] = translated
    return result
