#pragma makedep register
#pragma winrt ns_prefix

import "windows.ui.notifications.idl";

namespace Windows.UI.Notifications {
    runtimeclass BadgeUpdateManager;
    runtimeclass ToastNotification;
    runtimeclass ToastNotificationManager;
}
