/*
 * Delivery Optimization proxy registration
 *
 * Copyright 2026 Wine4Office project
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */

#pragma makedep ident proxy register

#include "deliveryoptimization.idl"

[
    threading(both),
    uuid(9e9f9b1c-7022-4f3c-a989-3debb803a16f)
]
coclass PSFactoryBuffer { interface IPSFactoryBuffer; }
