/* Windows.Web.Http interface definitions
 *
 * Copyright 2026 Wine contributors
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 */

#ifdef __WIDL__
#pragma winrt ns_prefix
#endif

import "inspectable.idl";
import "windows.foundation.idl";
import "windows.storage.streams.idl";
import "windows.security.credentials.idl";
namespace Windows.Security.Cryptography.Certificates
{
    typedef enum ChainValidationResult
    {
        Success = 0,
        Untrusted = 1,
        Revoked = 2,
        Expired = 3,
        IncompleteChain = 4,
        InvalidSignature = 5,
        WrongUsage = 6,
        InvalidName = 7,
        InvalidCertificateAuthorityPolicy = 8,
        BasicConstraintsError = 9,
        UnknownCriticalExtension = 10,
        RevocationInformationMissing = 11,
        RevocationFailure = 12,
        OtherErrors = 13,
    } ChainValidationResult;
}

namespace Windows.Security.Credentials
{
    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        uuid(6ab18989-c720-41a7-a6c1-feadb36329a0)
    ]
    interface IPasswordCredential : IInspectable
    {
        [propget] HRESULT Resource([out, retval] HSTRING *value);
        [propput] HRESULT Resource([in] HSTRING value);
        [propget] HRESULT UserName([out, retval] HSTRING *value);
        [propput] HRESULT UserName([in] HSTRING value);
        [propget] HRESULT Password([out, retval] HSTRING *value);
        [propput] HRESULT Password([in] HSTRING value);
    }
    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile), threading(both)]
    runtimeclass PasswordCredential
    {
        [default] interface Windows.Security.Credentials.IPasswordCredential;
    }
}

namespace Windows.Web.Http.Headers
{
    declare {
        interface Windows.Foundation.Collections.IKeyValuePair<HSTRING, HSTRING>;
        interface Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<HSTRING, HSTRING> *>;
        interface Windows.Foundation.Collections.IMap<HSTRING, HSTRING>;
    }
    interface IHttpRequestHeaderCollection;
    interface IHttpResponseHeaderCollection;
    interface IHttpContentHeaderCollection;
    runtimeclass HttpRequestHeaderCollection;
    runtimeclass HttpResponseHeaderCollection;
    runtimeclass HttpContentHeaderCollection;
}
namespace Windows.Web.Http.Filters
{
    interface IHttpFilter;
    interface IHttpBaseProtocolFilter;
    interface IHttpCacheControl;
    runtimeclass HttpBaseProtocolFilter;
    runtimeclass HttpCacheControl;
    declare {
        interface Windows.Foundation.Collections.IIterator<Windows.Security.Cryptography.Certificates.ChainValidationResult>;
        interface Windows.Foundation.Collections.IIterable<Windows.Security.Cryptography.Certificates.ChainValidationResult>;
        interface Windows.Foundation.Collections.IVectorView<Windows.Security.Cryptography.Certificates.ChainValidationResult>;
        interface Windows.Foundation.Collections.IVector<Windows.Security.Cryptography.Certificates.ChainValidationResult>;
    }
    typedef enum HttpCacheReadBehavior
    {
        Default = 0,
        MostRecent = 1,
        OnlyFromCache = 2,
        NoCache = 3,
    } HttpCacheReadBehavior;
    typedef enum HttpCacheWriteBehavior
    {
        Default = 0,
        NoCache = 1,
    } HttpCacheWriteBehavior;
}


namespace Windows.Web.Http
{
    typedef enum HttpCompletionOption
    {
        ResponseContentRead = 0,
        ResponseHeadersRead = 1,
    } HttpCompletionOption;

    typedef enum HttpProgressStage
    {
        None = 0,
        DetectingProxy = 10,
        ResolvingName = 20,
        ConnectingToServer = 30,
        NegotiatingSsl = 40,
        SendingHeaders = 50,
        SendingContent = 60,
        WaitingForResponse = 70,
        ReceivingHeaders = 80,
        ReceivingContent = 90
    } HttpProgressStage;

    typedef enum HttpResponseMessageSource
    {
        None = 0,
        Cache = 1,
        Network = 2
    } HttpResponseMessageSource;

    typedef enum HttpStatusCode
    {
        None = 0,
        Continue = 100,
        SwitchingProtocols = 101,
        Processing = 102,
        Ok = 200,
        Created = 201,
        Accepted = 202,
        NonAuthoritativeInformation = 203,
        NoContent = 204,
        ResetContent = 205,
        PartialContent = 206,
        MultipleChoices = 300,
        MovedPermanently = 301,
        Found = 302,
        SeeOther = 303,
        NotModified = 304,
        TemporaryRedirect = 307,
        PermanentRedirect = 308,
        BadRequest = 400,
        Unauthorized = 401,
        Forbidden = 403,
        NotFound = 404,
        MethodNotAllowed = 405,
        RequestTimeout = 408,
        Conflict = 409,
        Gone = 410,
        UnsupportedMediaType = 415,
        InternalServerError = 500,
        NotImplemented = 501,
        BadGateway = 502,
        ServiceUnavailable = 503,
        GatewayTimeout = 504,
        HttpVersionNotSupported = 505
    } HttpStatusCode;

    typedef enum HttpVersion
    {
        NoneVersion = 0,
        Http10 = 1,
        Http11 = 2,
        Http20 = 3
    } HttpVersion;

    typedef struct HttpProgress
    {
        HttpProgressStage Stage;
        UINT64 BytesSent;
        IInspectable *TotalBytesToSend;
        UINT64 BytesReceived;
        IInspectable *TotalBytesToReceive;
        UINT32 Retries;
    } HttpProgress;

    runtimeclass HttpMethod;
    interface IHttpMethod;
    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpMethod),
        uuid(728d4022-700d-4fe0-afa5-40299c58dbfd)
    ]
    interface IHttpMethod : IInspectable
    {
        [propget] HRESULT Method([out, retval] HSTRING *value);
    }
    interface IHttpClientFactory;
    interface IHttpContent;
    interface IHttpCookie;
    interface IHttpCookieFactory;
    interface IHttpCookieManager;
    interface IHttpRequestMessage;
    interface IHttpRequestMessageFactory;
    interface IHttpResponseMessage;
    interface IHttpResponseMessageFactory;
    interface IHttpTransportInformation;
    runtimeclass HttpClient;
    runtimeclass HttpContent;
    runtimeclass HttpCookie;
    runtimeclass HttpCookieCollection;
    runtimeclass HttpCookieManager;
    runtimeclass HttpMethod;
    runtimeclass HttpRequestMessage;
    runtimeclass HttpResponseMessage;
    declare {
        interface Windows.Foundation.IReference<UINT64>;
        interface Windows.Foundation.Collections.IIterable<Windows.Web.Http.HttpCookie *>;
        interface Windows.Foundation.Collections.IIterator<Windows.Web.Http.HttpCookie *>;
        interface Windows.Foundation.Collections.IVectorView<Windows.Web.Http.HttpCookie *>;
        interface Windows.Foundation.AsyncOperationProgressHandler<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.AsyncOperationWithProgressCompletedHandler<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.AsyncOperationProgressHandler<Windows.Storage.Streams.IBuffer *, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.AsyncOperationWithProgressCompletedHandler<Windows.Storage.Streams.IBuffer *, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.AsyncOperationProgressHandler<Windows.Storage.Streams.IInputStream *, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.AsyncOperationWithProgressCompletedHandler<Windows.Storage.Streams.IInputStream *, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.AsyncOperationProgressHandler<HSTRING, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.AsyncOperationWithProgressCompletedHandler<HSTRING, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.AsyncOperationProgressHandler<HSTRING, UINT64>;
        interface Windows.Foundation.AsyncOperationWithProgressCompletedHandler<HSTRING, UINT64>;
        interface Windows.Foundation.AsyncOperationProgressHandler<Windows.Storage.Streams.IBuffer *, UINT64>;
        interface Windows.Foundation.AsyncOperationWithProgressCompletedHandler<Windows.Storage.Streams.IBuffer *, UINT64>;
        interface Windows.Foundation.AsyncOperationProgressHandler<Windows.Storage.Streams.IInputStream *, UINT64>;
        interface Windows.Foundation.AsyncOperationWithProgressCompletedHandler<Windows.Storage.Streams.IInputStream *, UINT64>;
        interface Windows.Foundation.IAsyncOperationWithProgress<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.IAsyncOperationWithProgress<HSTRING, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.IAsyncOperationWithProgress<HSTRING, UINT64>;
        interface Windows.Foundation.IAsyncOperationWithProgress<UINT64, UINT64>;
        interface Windows.Foundation.IAsyncOperationWithProgress<Windows.Storage.Streams.IBuffer *, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.IAsyncOperationWithProgress<Windows.Storage.Streams.IInputStream *, Windows.Web.Http.HttpProgress>;
        interface Windows.Foundation.IAsyncOperationWithProgress<Windows.Storage.Streams.IBuffer *, UINT64>;
        interface Windows.Foundation.IAsyncOperationWithProgress<Windows.Storage.Streams.IInputStream *, UINT64>;
    }
    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpClient),
        uuid(7fda1151-3574-4880-a8ba-e6b1e0061f3d)
    ]
    interface IHttpClient : IInspectable
    {
        HRESULT DeleteAsync([in] Windows.Foundation.Uri *uri, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress> **operation);
        HRESULT GetAsync([in] Windows.Foundation.Uri *uri, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress> **operation);
        HRESULT GetWithOptionAsync([in] Windows.Foundation.Uri *uri, [in] Windows.Web.Http.HttpCompletionOption option, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress> **operation);
        HRESULT GetBufferAsync([in] Windows.Foundation.Uri *uri, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Storage.Streams.IBuffer *, Windows.Web.Http.HttpProgress> **operation);
        HRESULT GetInputStreamAsync([in] Windows.Foundation.Uri *uri, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Storage.Streams.IInputStream *, Windows.Web.Http.HttpProgress> **operation);
        HRESULT GetStringAsync([in] Windows.Foundation.Uri *uri, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<HSTRING, Windows.Web.Http.HttpProgress> **operation);
        HRESULT PostAsync([in] Windows.Foundation.Uri *uri, [in] Windows.Web.Http.IHttpContent *content, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress> **operation);
        HRESULT PutAsync([in] Windows.Foundation.Uri *uri, [in] Windows.Web.Http.IHttpContent *content, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress> **operation);
        HRESULT SendRequestAsync([in] Windows.Web.Http.HttpRequestMessage *request, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress> **operation);
        HRESULT SendRequestWithOptionAsync([in] Windows.Web.Http.HttpRequestMessage *request, [in] Windows.Web.Http.HttpCompletionOption option, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress> **operation);
        [propget] HRESULT DefaultRequestHeaders([out, retval] Windows.Web.Http.Headers.HttpRequestHeaderCollection **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpClient),
        uuid(c30c4eca-e3fa-4f99-afb4-63cc65009462)
    ]
    interface IHttpClientFactory : IInspectable
    {
        HRESULT Create([in] Windows.Web.Http.Filters.IHttpFilter *filter, [out, retval] Windows.Web.Http.HttpClient **client);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        uuid(6b14a441-fba7-4bd2-af0a-839de7c295da)
    ]
    interface IHttpContent : IInspectable
    {
        [propget] HRESULT Headers([out, retval] Windows.Web.Http.Headers.HttpContentHeaderCollection **value);
        HRESULT BufferAllAsync([out, retval] Windows.Foundation.IAsyncOperationWithProgress<UINT64, UINT64> **operation);
        HRESULT ReadAsBufferAsync([out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Storage.Streams.IBuffer *, UINT64> **operation);
        HRESULT ReadAsInputStreamAsync([out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Storage.Streams.IInputStream *, UINT64> **operation);
        HRESULT ReadAsStringAsync([out, retval] Windows.Foundation.IAsyncOperationWithProgress<HSTRING, UINT64> **operation);
        HRESULT TryComputeLength([out] UINT64 *length, [out, retval] boolean *succeeded);
        HRESULT WriteToStreamAsync([in] Windows.Storage.Streams.IOutputStream *outputStream, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<UINT64, UINT64> **operation);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpCookie),
        uuid(1f5488e2-cc2d-4779-86a7-88f10687d249)
    ]
    interface IHttpCookie : IInspectable
    {
        [propget] HRESULT Name([out, retval] HSTRING *value);
        [propget] HRESULT Domain([out, retval] HSTRING *value);
        [propget] HRESULT Path([out, retval] HSTRING *value);
        [propget] HRESULT Expires([out, retval] Windows.Foundation.IReference<Windows.Foundation.DateTime> **value);
        [propput] HRESULT Expires([in] Windows.Foundation.IReference<Windows.Foundation.DateTime> *value);
        [propget] HRESULT HttpOnly([out, retval] boolean *value);
        [propput] HRESULT HttpOnly([in] boolean value);
        [propget] HRESULT Secure([out, retval] boolean *value);
        [propput] HRESULT Secure([in] boolean value);
        [propget] HRESULT Value([out, retval] HSTRING *value);
        [propput] HRESULT Value([in] HSTRING value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpCookie),
        uuid(6a0585a9-931c-4cd1-a96d-c21701785c5f)
    ]
    interface IHttpCookieFactory : IInspectable
    {
        HRESULT Create([in] HSTRING name, [in] HSTRING domain, [in] HSTRING path, [out, retval] Windows.Web.Http.HttpCookie **cookie);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpCookieManager),
        uuid(7a431780-cd4f-4e57-a84a-5b0a53d6bb96)
    ]
    interface IHttpCookieManager : IInspectable
    {
        HRESULT SetCookie([in] Windows.Web.Http.HttpCookie *cookie, [out, retval] boolean *replaced);
        HRESULT SetCookieWithThirdParty([in] Windows.Web.Http.HttpCookie *cookie, [in] boolean thirdParty, [out, retval] boolean *replaced);
        HRESULT DeleteCookie([in] Windows.Web.Http.HttpCookie *cookie);
        HRESULT GetCookies([in] Windows.Foundation.Uri *uri, [out, retval] Windows.Web.Http.HttpCookieCollection **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpRequestMessage),
        uuid(f5762b3c-74d4-4811-b5dc-9f8b4e2f9abf)
    ]
    interface IHttpRequestMessage : IInspectable
    {
        [propget] HRESULT Content([out, retval] Windows.Web.Http.IHttpContent **value);
        [propput] HRESULT Content([in] Windows.Web.Http.IHttpContent *value);
        [propget] HRESULT Headers([out, retval] Windows.Web.Http.Headers.HttpRequestHeaderCollection **value);
        [propget] HRESULT Method([out, retval] Windows.Web.Http.HttpMethod **value);
        [propput] HRESULT Method([in] Windows.Web.Http.HttpMethod *value);
        [propget] HRESULT RequestUri([out, retval] Windows.Foundation.Uri **value);
        [propput] HRESULT RequestUri([in] Windows.Foundation.Uri *value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpRequestMessage),
        uuid(5bac994e-3886-412e-aec3-52ec7f25616f)
    ]
    interface IHttpRequestMessageFactory : IInspectable
    {
        HRESULT Create([in] Windows.Web.Http.HttpMethod *method, [in] Windows.Foundation.Uri *uri, [out, retval] Windows.Web.Http.HttpRequestMessage **message);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpResponseMessage),
        uuid(fee200fb-8664-44e0-95d9-42696199bffc)
    ]
    interface IHttpResponseMessage : IInspectable
    {
        [propget] HRESULT Content([out, retval] Windows.Web.Http.IHttpContent **value);
        [propput] HRESULT Content([in] Windows.Web.Http.IHttpContent *value);
        [propget] HRESULT Headers([out, retval] Windows.Web.Http.Headers.HttpResponseHeaderCollection **value);
        [propget] HRESULT IsSuccessStatusCode([out, retval] boolean *value);
        [propget] HRESULT ReasonPhrase([out, retval] HSTRING *value);
        [propput] HRESULT ReasonPhrase([in] HSTRING value);
        [propget] HRESULT RequestMessage([out, retval] Windows.Web.Http.HttpRequestMessage **value);
        [propput] HRESULT RequestMessage([in] Windows.Web.Http.HttpRequestMessage *value);
        [propget] HRESULT Source([out, retval] Windows.Web.Http.HttpResponseMessageSource *value);
        [propput] HRESULT Source([in] Windows.Web.Http.HttpResponseMessageSource value);
        [propget] HRESULT StatusCode([out, retval] Windows.Web.Http.HttpStatusCode *value);
        [propput] HRESULT StatusCode([in] Windows.Web.Http.HttpStatusCode value);
        [propget] HRESULT Version([out, retval] Windows.Web.Http.HttpVersion *value);
        [propput] HRESULT Version([in] Windows.Web.Http.HttpVersion value);
        HRESULT EnsureSuccessStatusCode([out, retval] Windows.Web.Http.HttpResponseMessage **message);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.Web.Http.HttpResponseMessage),
        uuid(52a8af99-f095-43da-b60f-7cfc2bc7ea2f)
    ]
    interface IHttpResponseMessageFactory : IInspectable
    {
        HRESULT Create([in] Windows.Web.Http.HttpStatusCode statusCode, [out, retval] Windows.Web.Http.HttpResponseMessage **message);
    }

    [
        activatable(Windows.Foundation.UniversalApiContract, 1.0),
        activatable(Windows.Web.Http.IHttpClientFactory, Windows.Foundation.UniversalApiContract, 1.0),
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass HttpClient
    {
        [default] interface Windows.Web.Http.IHttpClient;
        interface Windows.Foundation.IClosable;
        interface Windows.Foundation.IStringable;
    }
    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile), threading(both)]
    runtimeclass HttpMethod
    {
        [default] interface Windows.Web.Http.IHttpMethod;
        interface Windows.Foundation.IStringable;
    }

    [
        activatable(Windows.Foundation.UniversalApiContract, 1.0),
        activatable(Windows.Web.Http.IHttpCookieFactory, Windows.Foundation.UniversalApiContract, 1.0),
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass HttpCookie
    {
        [default] interface Windows.Web.Http.IHttpCookie;
        interface Windows.Foundation.IStringable;
    }

    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile), threading(both)]
    runtimeclass HttpCookieCollection
    {
        [default] interface Windows.Foundation.Collections.IVectorView<Windows.Web.Http.HttpCookie *>;
        interface Windows.Foundation.Collections.IIterable<Windows.Web.Http.HttpCookie *>;
    }

    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile), threading(both)]
    runtimeclass HttpCookieManager
    {
        [default] interface Windows.Web.Http.IHttpCookieManager;
    }

    [
        activatable(Windows.Foundation.UniversalApiContract, 1.0),
        activatable(Windows.Web.Http.IHttpRequestMessageFactory, Windows.Foundation.UniversalApiContract, 1.0),
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass HttpRequestMessage
    {
        [default] interface Windows.Web.Http.IHttpRequestMessage;
        interface Windows.Foundation.IClosable;
        interface Windows.Foundation.IStringable;
    }

    [
        activatable(Windows.Foundation.UniversalApiContract, 1.0),
        activatable(Windows.Web.Http.IHttpResponseMessageFactory, Windows.Foundation.UniversalApiContract, 1.0),
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass HttpResponseMessage
    {
        [default] interface Windows.Web.Http.IHttpResponseMessage;
        interface Windows.Foundation.IClosable;
        interface Windows.Foundation.IStringable;
    }
}

namespace Windows.Web.Http.Headers
{
    [contract(Windows.Foundation.UniversalApiContract, 1.0), uuid(af40329b-b544-469b-86b9-ac3d466fea36)]
    interface IHttpRequestHeaderCollection : IInspectable
        requires Windows.Foundation.Collections.IMap<HSTRING, HSTRING>, Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<HSTRING, HSTRING> *>
    {
        HRESULT Append([in] HSTRING name, [in] HSTRING value);
        HRESULT TryAppendWithoutValidation([in] HSTRING name, [in] HSTRING value, [out, retval] boolean *succeeded);
    }

    [contract(Windows.Foundation.UniversalApiContract, 1.0), uuid(7a990969-fa3f-41ed-aac6-bf957975c16b)]
    interface IHttpResponseHeaderCollection : IInspectable
        requires Windows.Foundation.Collections.IMap<HSTRING, HSTRING>, Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<HSTRING, HSTRING> *>
    {
        HRESULT Append([in] HSTRING name, [in] HSTRING value);
        HRESULT TryAppendWithoutValidation([in] HSTRING name, [in] HSTRING value, [out, retval] boolean *succeeded);
    }

    [contract(Windows.Foundation.UniversalApiContract, 1.0), uuid(40612a44-47ae-4b7e-9124-69628b64aa18)]
    interface IHttpContentHeaderCollection : IInspectable
        requires Windows.Foundation.Collections.IMap<HSTRING, HSTRING>, Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<HSTRING, HSTRING> *>
    {
        HRESULT Append([in] HSTRING name, [in] HSTRING value);
        HRESULT TryAppendWithoutValidation([in] HSTRING name, [in] HSTRING value, [out, retval] boolean *succeeded);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass HttpRequestHeaderCollection
    {
        [default] interface Windows.Web.Http.Headers.IHttpRequestHeaderCollection;
        interface Windows.Foundation.Collections.IMap<HSTRING, HSTRING>;
        interface Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<HSTRING, HSTRING> *>;
    }
    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass HttpResponseHeaderCollection
    {
        [default] interface Windows.Web.Http.Headers.IHttpResponseHeaderCollection;
        interface Windows.Foundation.Collections.IMap<HSTRING, HSTRING>;
        interface Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<HSTRING, HSTRING> *>;
    }
    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        threading(both)
    ]
    runtimeclass HttpContentHeaderCollection
    {
        [default] interface Windows.Web.Http.Headers.IHttpContentHeaderCollection;
        interface Windows.Foundation.Collections.IMap<HSTRING, HSTRING>;
        interface Windows.Foundation.Collections.IIterable<Windows.Foundation.Collections.IKeyValuePair<HSTRING, HSTRING> *>;
    }

}
namespace Windows.Web.Http.Filters
{

    [contract(Windows.Foundation.UniversalApiContract, 1.0), uuid(a4cb6dd5-0902-439e-bfd7-e12552b165ce)]
    interface IHttpFilter : IInspectable
    {
        HRESULT SendRequestAsync([in] Windows.Web.Http.HttpRequestMessage *request, [out, retval] Windows.Foundation.IAsyncOperationWithProgress<Windows.Web.Http.HttpResponseMessage *, Windows.Web.Http.HttpProgress> **operation);
    }

    [contract(Windows.Foundation.UniversalApiContract, 1.0), exclusiveto(Windows.Web.Http.Filters.HttpBaseProtocolFilter), uuid(71c89b09-e131-4b54-a53c-eb43ff37e9bb)]
    interface IHttpBaseProtocolFilter : IInspectable
    {
        [propget] HRESULT AllowAutoRedirect([out, retval] boolean *value);
        [propput] HRESULT AllowAutoRedirect([in] boolean value);
        [propget] HRESULT AllowUI([out, retval] boolean *value);
        [propput] HRESULT AllowUI([in] boolean value);
        [propget] HRESULT AutomaticDecompression([out, retval] boolean *value);
        [propput] HRESULT AutomaticDecompression([in] boolean value);
        [propget] HRESULT CacheControl([out, retval] Windows.Web.Http.Filters.HttpCacheControl **value);
        [propget] HRESULT CookieManager([out, retval] Windows.Web.Http.HttpCookieManager **value);
        [propget] HRESULT ClientCertificate([out, retval] IInspectable **value);
        [propput] HRESULT ClientCertificate([in] IInspectable *value);
        [propget] HRESULT IgnorableServerCertificateErrors([out, retval] Windows.Foundation.Collections.IVector<Windows.Security.Cryptography.Certificates.ChainValidationResult> **value);
        [propget] HRESULT MaxConnectionsPerServer([out, retval] UINT32 *value);
        [propput] HRESULT MaxConnectionsPerServer([in] UINT32 value);
        [propget] HRESULT ProxyCredential([out, retval] Windows.Security.Credentials.PasswordCredential **value);
        [propput] HRESULT ProxyCredential([in] Windows.Security.Credentials.PasswordCredential *value);
        [propget] HRESULT ServerCredential([out, retval] Windows.Security.Credentials.PasswordCredential **value);
        [propput] HRESULT ServerCredential([in] Windows.Security.Credentials.PasswordCredential *value);
        [propget] HRESULT UseProxy([out, retval] boolean *value);
        [propput] HRESULT UseProxy([in] boolean value);
    }

    [contract(Windows.Foundation.UniversalApiContract, 1.0), exclusiveto(Windows.Web.Http.Filters.HttpCacheControl), uuid(c77e1cb4-3cea-4eb5-ac85-04e186e63ab7)]
    interface IHttpCacheControl : IInspectable
    {
        [propget] HRESULT ReadBehavior([out, retval] Windows.Web.Http.Filters.HttpCacheReadBehavior *value);
        [propput] HRESULT ReadBehavior([in] Windows.Web.Http.Filters.HttpCacheReadBehavior value);
        [propget] HRESULT WriteBehavior([out, retval] Windows.Web.Http.Filters.HttpCacheWriteBehavior *value);
        [propput] HRESULT WriteBehavior([in] Windows.Web.Http.Filters.HttpCacheWriteBehavior value);
    }

    [activatable(Windows.Foundation.UniversalApiContract, 1.0), contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile), threading(both)]
    runtimeclass HttpBaseProtocolFilter
    {
        [default] interface Windows.Web.Http.Filters.IHttpBaseProtocolFilter;
        interface Windows.Web.Http.Filters.IHttpFilter;
        interface Windows.Foundation.IClosable;
    }

    [contract(Windows.Foundation.UniversalApiContract, 1.0), marshaling_behavior(agile), threading(both)]
    runtimeclass HttpCacheControl
    {
        [default] interface Windows.Web.Http.Filters.IHttpCacheControl;
    }
}
