/* Windows.ApplicationModel.Calls interface definitions. */

#ifdef __WIDL__
#pragma makedep header install winmd
#pragma winrt ns_prefix
#endif

import "windows.foundation.idl";

namespace Windows.ApplicationModel.Calls
{
    runtimeclass VoipCallCoordinator;

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        exclusiveto(Windows.ApplicationModel.Calls.VoipCallCoordinator),
        uuid(7f5d1f2b-e04a-4d10-b31a-a55c922cc2fb)
    ]
    interface IVoipCallCoordinatorStatics : IInspectable
    {
        HRESULT GetDefault([out, retval] IInspectable **value);
    }

    [
        contract(Windows.Foundation.UniversalApiContract, 1.0),
        marshaling_behavior(agile),
        static(Windows.ApplicationModel.Calls.IVoipCallCoordinatorStatics,
                Windows.Foundation.UniversalApiContract, 1.0),
        threading(both)
    ]
    runtimeclass VoipCallCoordinator
    {
    }
}
